
name: go-lint

# Controls when the action will run. Triggers the workflow on every push, this can be changed if it is over cautious
on: push

# currently a single job to carry out the scanning, in the future additional steps could be added for additional checks
jobs:
  # This workflow contains a single job called "scan"
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: Jerome1337/golint-action@v1.0.2
      with:
        golint-path: './...'
